spring:
  config:
    activate:
      on-profile: "redis"
    import: optional:file:*.env

  data:
    redis:
      host: ${REDIS_HOST_NAME}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}