spring:
  config:
    activate:
      on-profile: "prod"
    import: optional:file:*.env

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}


# geoip2
geoip2:
  database:
    path: /db/GeoLite2-Country.mmdb