name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - deploy  # main 브랜치에 푸시될 때만 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # GitHub Actions 기본 제공 체크아웃 액션
      - name: Checkout code
        uses: actions/checkout@v2

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      
#      # 환경변수 복사
#      - name : Extract .env
#        run: |
#          touch ./prod.env
#          echo "${{ secrets.ENV }}" > ./prod.env

      # Gradle 빌드
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      # Docker 로그인을 통해 DockerHub로 인증
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Docker 이미지를 빌드하고 DockerHub로 푸시
      - name: Build and push Docker image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/persist:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/persist:latest
  
  

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Prometheus 설정 파일을 원격 서버로 복사
      - name: Upload Prometheus config file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./prometheus.yml"
          target: "/home/ubuntu/"

      # docker compose 설정 파일을 원격 서버로 복사
      - name: Upload Prometheus config file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./docker-compose.yaml"
          target: "/home/ubuntu/"


      # SSH를 통해 원격 서버에 접속하고 Docker 이미지를 pull한 후 컨테이너 실행
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            
            # 환경변수 복사
            sudo touch ~/.env
            echo "${{ secrets.ENV }}" > ~/.env
            
            # docker pull 
            docker pull ${{ secrets.DOCKER_USERNAME }}/persist:latest
            
            # docker compose 중지
            docker compose down
            
            # docker compose 실행
            docker compose up -d
            
            # 사용되지 않는 이미지 삭제
            docker image prune -a -f
